[package]
name = "grt-bible"
version.workspace = true
description = "Local Bible reader for the Catholic canon"
authors.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "grt_bible_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { workspace = true }
serde_json = { workspace = true }
grtb = { path = "../crates/grtb" }
zip = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
tauri-plugin-fs = "2"

[dev-dependencies]
tempfile = "3"
